name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a compatible Node.js version (e.g., 18 or 20)

      - name: Environment Variable
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR" 
          echo "Vite: $vars.VITE_API_KEY"
          echo "Vite: $secrets.VITE_API_KEY"
          echo "Vite: $env.VITE_API_KEY"
          echo "Vite: $VITE_API_KEY"
          echo "${{ env.Greeting }} ${{ env.First_Name }}. Today is ${{ env.DAY_OF_WEEK }}!"
          echo "env -> ${{ env.VITE_API_KEY }}, vars -> ${{ vars.VITE_API_KEY }}, secrets -> ${{ secrets.VITE_API_KEY }}"
          echo "Repository -> ${{github.repository}}, VITE_API_KEY -> ${{github.env.secrets.VITE_API_KEY}}"

      - name: Install dependencies
        run: npm install

      - name: Build application
        #env:
        # Access the secret/variable and assign it to an environment variable name
        #VITE_API_KEY:
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist # The folder where your build artifacts are located
